#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/syslink/utils/rtos/bios6
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/include/utils.tci
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/_config.bld:
package.mak: /home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/_config.bld
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
package.mak: package.bld
/home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/ti/syslink/buildutils/rtos/buildScripts/common.bld:
package.mak: /home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/ti/syslink/buildutils/rtos/buildScripts/common.bld
endif

ti.targets.elf.C674.rootDir ?= /home/chandler/Dev_J5ECO/dsp-devkit/cgt6x_7_3_4
ti.targets.elf.packageBase ?= /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.syslink.utils.rtos.bios6.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.syslink.utils.rtos.bios6" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.syslink.utils.rtos.bios6 $@

.libraries,e674 .libraries: lib/debug/ti.syslink.utils.rtos.bios6.ae674

-include lib/debug/ti.syslink.utils.rtos.bios6.ae674.mak
lib/debug/ti.syslink.utils.rtos.bios6.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Trace.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Cfg.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Trace.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Cfg.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oe674 
lib/debug/ti.syslink.utils.rtos.bios6.ae674: export C_DIR=
lib/debug/ti.syslink.utils.rtos.bios6.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/debug/ti.syslink.utils.rtos.bios6.ae674
.libraries,e674 .libraries: lib/release/ti.syslink.utils.rtos.bios6.ae674

-include lib/release/ti.syslink.utils.rtos.bios6.ae674.mak
lib/release/ti.syslink.utils.rtos.bios6.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Trace.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Cfg.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Trace.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Cfg.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oe674 
lib/release/ti.syslink.utils.rtos.bios6.ae674: export C_DIR=
lib/release/ti.syslink.utils.rtos.bios6.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/release/ti.syslink.utils.rtos.bios6.ae674
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.syslink.utils.rtos.bios6.oe674,copy
package_ti.syslink.utils.rtos.bios6.oe674,copy : package_ti.syslink.utils.rtos.bios6.oe674,0,copy package_ti.syslink.utils.rtos.bios6.oe674,1,copy 
	@

package_ti.syslink.utils.rtos.bios6.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674
package_ti.syslink.utils.rtos.bios6.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674
.PHONY: package_ti.syslink.utils.rtos.bios6.se674,copy
package_ti.syslink.utils.rtos.bios6.se674,copy : package_ti.syslink.utils.rtos.bios6.se674,0,copy package_ti.syslink.utils.rtos.bios6.se674,1,copy 
	@

package_ti.syslink.utils.rtos.bios6.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.se674
package_ti.syslink.utils.rtos.bios6.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.se674
.PHONY: OsalPrint.oe674,copy
OsalPrint.oe674,copy : OsalPrint.oe674,0,copy OsalPrint.oe674,1,copy 
	@

OsalPrint.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.oe674
OsalPrint.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.oe674
.PHONY: OsalPrint.se674,copy
OsalPrint.se674,copy : OsalPrint.se674,0,copy OsalPrint.se674,1,copy 
	@

OsalPrint.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.se674
OsalPrint.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalPrint.se674
.PHONY: OsalKfile.oe674,copy
OsalKfile.oe674,copy : OsalKfile.oe674,0,copy OsalKfile.oe674,1,copy 
	@

OsalKfile.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.oe674
OsalKfile.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.oe674
.PHONY: OsalKfile.se674,copy
OsalKfile.se674,copy : OsalKfile.se674,0,copy OsalKfile.se674,1,copy 
	@

OsalKfile.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.se674
OsalKfile.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/OsalKfile.se674
.PHONY: MemoryOS.oe674,copy
MemoryOS.oe674,copy : MemoryOS.oe674,0,copy MemoryOS.oe674,1,copy 
	@

MemoryOS.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.oe674
MemoryOS.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.oe674
.PHONY: MemoryOS.se674,copy
MemoryOS.se674,copy : MemoryOS.se674,0,copy MemoryOS.se674,1,copy 
	@

MemoryOS.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.se674
MemoryOS.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6/MemoryOS.se674
.PHONY: Trace.oe674,copy
Trace.oe674,copy : Trace.oe674,0,copy Trace.oe674,1,copy 
	@

Trace.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Trace.oe674
Trace.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Trace.oe674
.PHONY: Trace.se674,copy
Trace.se674,copy : Trace.se674,0,copy Trace.se674,1,copy 
	@

Trace.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Trace.se674
Trace.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Trace.se674
.PHONY: Cfg.oe674,copy
Cfg.oe674,copy : Cfg.oe674,0,copy Cfg.oe674,1,copy 
	@

Cfg.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Cfg.oe674
Cfg.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Cfg.oe674
.PHONY: Cfg.se674,copy
Cfg.se674,copy : Cfg.se674,0,copy Cfg.se674,1,copy 
	@

Cfg.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common/Cfg.se674
Cfg.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common/Cfg.se674
.PHONY: TraceDrv.oe674,copy
TraceDrv.oe674,copy : TraceDrv.oe674,0,copy TraceDrv.oe674,1,copy 
	@

TraceDrv.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oe674
TraceDrv.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oe674
.PHONY: TraceDrv.se674,copy
TraceDrv.se674,copy : TraceDrv.se674,0,copy TraceDrv.se674,1,copy 
	@

TraceDrv.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.se674
TraceDrv.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.se674

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_syslink_utils_rtos_bios6
ti_syslink_utils_rtos_bios6.tar: package/package.bld.xml
ti_syslink_utils_rtos_bios6.tar: package/package.ext.xml
ti_syslink_utils_rtos_bios6.tar: package/package.rel.dot
ti_syslink_utils_rtos_bios6.tar: package/build.cfg
ti_syslink_utils_rtos_bios6.tar: package/package.xdc.inc
ti_syslink_utils_rtos_bios6.tar: package/package.cfg.xdc.inc
ti_syslink_utils_rtos_bios6.tar: lib/debug/ti.syslink.utils.rtos.bios6.ae674
ti_syslink_utils_rtos_bios6.tar: lib/release/ti.syslink.utils.rtos.bios6.ae674
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_syslink_utils_rtos_bios6.tar.dep
endif
package/rel/ti_syslink_utils_rtos_bios6/ti/syslink/utils/rtos/bios6/package/package.rel.xml:

ti_syslink_utils_rtos_bios6.tar: package/rel/ti_syslink_utils_rtos_bios6.xdc.inc package/rel/ti_syslink_utils_rtos_bios6/ti/syslink/utils/rtos/bios6/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_syslink_utils_rtos_bios6.xdc.inc,package/rel/ti_syslink_utils_rtos_bios6.tar.dep)


release release,ti_syslink_utils_rtos_bios6: all ti_syslink_utils_rtos_bios6.tar
clean:: .clean
	-$(RM) ti_syslink_utils_rtos_bios6.tar
	-$(RM) package/rel/ti_syslink_utils_rtos_bios6.xdc.inc
	-$(RM) package/rel/ti_syslink_utils_rtos_bios6.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/debug))
    $(shell $(MKDIR) lib/debug)
endif
ifeq (,$(wildcard lib/release))
    $(shell $(MKDIR) lib/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/debug))
    $(shell $(MKDIR) package/lib/lib/debug)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/..))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/..)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../osal/bios6)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../..))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../..)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/../../common)
endif
ifeq (,$(wildcard package/lib/lib/release))
    $(shell $(MKDIR) package/lib/lib/release)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/package))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/package)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/..))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/..)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/../osal/bios6)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/../..))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/../..)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/../../common)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.syslink.utils.rtos.bios6.pjt
