#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/syslink/ipc/rtos
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/include/utils.tci
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/template.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/package.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/_config.bld:
package.mak: /home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/_config.bld
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
package.mak: package.bld
/home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/ti/syslink/buildutils/rtos/buildScripts/common.bld:
package.mak: /home/chandler/Dev_J5ECO/component-sources/syslink_2_20_02_20/packages/ti/syslink/buildutils/rtos/buildScripts/common.bld
endif

ti.targets.elf.C674.rootDir ?= /home/chandler/Dev_J5ECO/dsp-devkit/cgt6x_7_3_4
ti.targets.elf.packageBase ?= /home/chandler/Dev_J5ECO/component-sources/xdctools_3_23_03_53/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.syslink.ipc.rtos.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.syslink.ipc.rtos" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.syslink.ipc.rtos $@

.libraries,e674 .libraries: lib/debug/ti.syslink.ipc.rtos.ae674

-include lib/debug/ti.syslink.ipc.rtos.ae674.mak
lib/debug/ti.syslink.ipc.rtos.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../ClientNotifyMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIO.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIOShm.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/_Syslink.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/Syslink.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQBufMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQ.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../ClientNotifyMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIO.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIOShm.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/_Syslink.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/Syslink.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQBufMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQ.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.oe674 package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.oe674 
lib/debug/ti.syslink.ipc.rtos.ae674: export C_DIR=
lib/debug/ti.syslink.ipc.rtos.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/debug/ti.syslink.ipc.rtos.ae674
.libraries,e674 .libraries: lib/release/ti.syslink.ipc.rtos.ae674

-include lib/release/ti.syslink.ipc.rtos.ae674.mak
lib/release/ti.syslink.ipc.rtos.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../ClientNotifyMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIO.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIOShm.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/_Syslink.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/Syslink.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/FrameQBufMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/FrameQ.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../ClientNotifyMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIO.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIOShm.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/_Syslink.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/Syslink.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/FrameQBufMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/FrameQ.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.oe674 package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.oe674 
lib/release/ti.syslink.ipc.rtos.ae674: export C_DIR=
lib/release/ti.syslink.ipc.rtos.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/release/ti.syslink.ipc.rtos.ae674
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.syslink.ipc.rtos.oe674,copy
package_ti.syslink.ipc.rtos.oe674,copy : package_ti.syslink.ipc.rtos.oe674,0,copy package_ti.syslink.ipc.rtos.oe674,1,copy 
	@

package_ti.syslink.ipc.rtos.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.oe674
package_ti.syslink.ipc.rtos.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.oe674
.PHONY: package_ti.syslink.ipc.rtos.se674,copy
package_ti.syslink.ipc.rtos.se674,copy : package_ti.syslink.ipc.rtos.se674,0,copy package_ti.syslink.ipc.rtos.se674,1,copy 
	@

package_ti.syslink.ipc.rtos.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.se674
package_ti.syslink.ipc.rtos.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/package/package_ti.syslink.ipc.rtos.se674
.PHONY: SysLinkCfg.oe674,copy
SysLinkCfg.oe674,copy : SysLinkCfg.oe674,0,copy SysLinkCfg.oe674,1,copy 
	@

SysLinkCfg.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.oe674
SysLinkCfg.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.oe674
.PHONY: SysLinkCfg.se674,copy
SysLinkCfg.se674,copy : SysLinkCfg.se674,0,copy SysLinkCfg.se674,1,copy 
	@

SysLinkCfg.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.se674
SysLinkCfg.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../cfg/SysLinkCfg.se674
.PHONY: ClientNotifyMgr.oe674,copy
ClientNotifyMgr.oe674,copy : ClientNotifyMgr.oe674,0,copy ClientNotifyMgr.oe674,1,copy 
	@

ClientNotifyMgr.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../ClientNotifyMgr.oe674
ClientNotifyMgr.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../ClientNotifyMgr.oe674
.PHONY: ClientNotifyMgr.se674,copy
ClientNotifyMgr.se674,copy : ClientNotifyMgr.se674,0,copy ClientNotifyMgr.se674,1,copy 
	@

ClientNotifyMgr.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../ClientNotifyMgr.se674
ClientNotifyMgr.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../ClientNotifyMgr.se674
.PHONY: RingIO.oe674,copy
RingIO.oe674,copy : RingIO.oe674,0,copy RingIO.oe674,1,copy 
	@

RingIO.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIO.oe674
RingIO.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIO.oe674
.PHONY: RingIO.se674,copy
RingIO.se674,copy : RingIO.se674,0,copy RingIO.se674,1,copy 
	@

RingIO.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIO.se674
RingIO.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIO.se674
.PHONY: RingIOShm.oe674,copy
RingIOShm.oe674,copy : RingIOShm.oe674,0,copy RingIOShm.oe674,1,copy 
	@

RingIOShm.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIOShm.oe674
RingIOShm.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIOShm.oe674
.PHONY: RingIOShm.se674,copy
RingIOShm.se674,copy : RingIOShm.se674,0,copy RingIOShm.se674,1,copy 
	@

RingIOShm.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/../../RingIOShm.se674
RingIOShm.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/../../RingIOShm.se674
.PHONY: _Syslink.oe674,copy
_Syslink.oe674,copy : _Syslink.oe674,0,copy _Syslink.oe674,1,copy 
	@

_Syslink.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/_Syslink.oe674
_Syslink.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/_Syslink.oe674
.PHONY: _Syslink.se674,copy
_Syslink.se674,copy : _Syslink.se674,0,copy _Syslink.se674,1,copy 
	@

_Syslink.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/_Syslink.se674
_Syslink.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/_Syslink.se674
.PHONY: Syslink.oe674,copy
Syslink.oe674,copy : Syslink.oe674,0,copy Syslink.oe674,1,copy 
	@

Syslink.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/Syslink.oe674
Syslink.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/Syslink.oe674
.PHONY: Syslink.se674,copy
Syslink.se674,copy : Syslink.se674,0,copy Syslink.se674,1,copy 
	@

Syslink.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/Syslink.se674
Syslink.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/Syslink.se674
.PHONY: FrameQBufMgr.oe674,copy
FrameQBufMgr.oe674,copy : FrameQBufMgr.oe674,0,copy FrameQBufMgr.oe674,1,copy 
	@

FrameQBufMgr.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQBufMgr.oe674
FrameQBufMgr.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/FrameQBufMgr.oe674
.PHONY: FrameQBufMgr.se674,copy
FrameQBufMgr.se674,copy : FrameQBufMgr.se674,0,copy FrameQBufMgr.se674,1,copy 
	@

FrameQBufMgr.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQBufMgr.se674
FrameQBufMgr.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/FrameQBufMgr.se674
.PHONY: FrameQ.oe674,copy
FrameQ.oe674,copy : FrameQ.oe674,0,copy FrameQ.oe674,1,copy 
	@

FrameQ.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQ.oe674
FrameQ.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/FrameQ.oe674
.PHONY: FrameQ.se674,copy
FrameQ.se674,copy : FrameQ.se674,0,copy FrameQ.se674,1,copy 
	@

FrameQ.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/FrameQ.se674
FrameQ.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/FrameQ.se674
.PHONY: FrameQ_ShMem.oe674,copy
FrameQ_ShMem.oe674,copy : FrameQ_ShMem.oe674,0,copy FrameQ_ShMem.oe674,1,copy 
	@

FrameQ_ShMem.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.oe674
FrameQ_ShMem.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.oe674
.PHONY: FrameQ_ShMem.se674,copy
FrameQ_ShMem.se674,copy : FrameQ_ShMem.se674,0,copy FrameQ_ShMem.se674,1,copy 
	@

FrameQ_ShMem.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.se674
FrameQ_ShMem.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQ_ShMem.se674
.PHONY: FrameQBufMgr_ShMem.oe674,copy
FrameQBufMgr_ShMem.oe674,copy : FrameQBufMgr_ShMem.oe674,0,copy FrameQBufMgr_ShMem.oe674,1,copy 
	@

FrameQBufMgr_ShMem.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.oe674
FrameQBufMgr_ShMem.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.oe674
.PHONY: FrameQBufMgr_ShMem.se674,copy
FrameQBufMgr_ShMem.se674,copy : FrameQBufMgr_ShMem.se674,0,copy FrameQBufMgr_ShMem.se674,1,copy 
	@

FrameQBufMgr_ShMem.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.se674
FrameQBufMgr_ShMem.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/shMem/FrameQBufMgr_ShMem.se674
.PHONY: SyslinkMemMgr.oe674,copy
SyslinkMemMgr.oe674,copy : SyslinkMemMgr.oe674,0,copy SyslinkMemMgr.oe674,1,copy 
	@

SyslinkMemMgr.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.oe674
SyslinkMemMgr.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.oe674
.PHONY: SyslinkMemMgr.se674,copy
SyslinkMemMgr.se674,copy : SyslinkMemMgr.se674,0,copy SyslinkMemMgr.se674,1,copy 
	@

SyslinkMemMgr.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.se674
SyslinkMemMgr.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/SyslinkMemMgr.se674
.PHONY: SharedMemoryMgr.oe674,copy
SharedMemoryMgr.oe674,copy : SharedMemoryMgr.oe674,0,copy SharedMemoryMgr.oe674,1,copy 
	@

SharedMemoryMgr.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.oe674
SharedMemoryMgr.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.oe674
.PHONY: SharedMemoryMgr.se674,copy
SharedMemoryMgr.se674,copy : SharedMemoryMgr.se674,0,copy SharedMemoryMgr.se674,1,copy 
	@

SharedMemoryMgr.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.se674
SharedMemoryMgr.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr/SharedMemoryMgr.se674
.PHONY: TilerMemoryMgr.oe674,copy
TilerMemoryMgr.oe674,copy : TilerMemoryMgr.oe674,0,copy TilerMemoryMgr.oe674,1,copy 
	@

TilerMemoryMgr.oe674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.oe674
TilerMemoryMgr.oe674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.oe674
.PHONY: TilerMemoryMgr.se674,copy
TilerMemoryMgr.se674,copy : TilerMemoryMgr.se674,0,copy TilerMemoryMgr.se674,1,copy 
	@

TilerMemoryMgr.se674,0,copy : package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.se674
TilerMemoryMgr.se674,1,copy : package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr/TilerMemoryMgr.se674

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti.syslink.ipc.rtos,src
ti.syslink.ipc.rtos,src.tar: package/package.bld.xml
ti.syslink.ipc.rtos,src.tar: package/package.ext.xml
ti.syslink.ipc.rtos,src.tar: package/package.rel.dot
ti.syslink.ipc.rtos,src.tar: package/build.cfg
ti.syslink.ipc.rtos,src.tar: package/package.xdc.inc
ti.syslink.ipc.rtos,src.tar: package/package.cfg.xdc.inc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti.syslink.ipc.rtos,src.tar.dep
endif
package/rel/ti.syslink.ipc.rtos,src/ti/syslink/ipc/rtos/package/package.rel.xml:

ti.syslink.ipc.rtos,src.tar: package/rel/ti.syslink.ipc.rtos,src.xdc.inc package/rel/ti.syslink.ipc.rtos,src/ti/syslink/ipc/rtos/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti.syslink.ipc.rtos$(comma)src.xdc.inc,package/rel/ti.syslink.ipc.rtos$(comma)src.tar.dep)


release release,ti.syslink.ipc.rtos,src: all ti.syslink.ipc.rtos,src.tar
clean:: .clean
	-$(RM) ti.syslink.ipc.rtos,src.tar
	-$(RM) package/rel/ti.syslink.ipc.rtos,src.xdc.inc
	-$(RM) package/rel/ti.syslink.ipc.rtos,src.tar.dep


.PHONY: release,ti_syslink_ipc_rtos
ti_syslink_ipc_rtos.tar: package/package.bld.xml
ti_syslink_ipc_rtos.tar: package/package.ext.xml
ti_syslink_ipc_rtos.tar: package/package.rel.dot
ti_syslink_ipc_rtos.tar: package/build.cfg
ti_syslink_ipc_rtos.tar: package/package.xdc.inc
ti_syslink_ipc_rtos.tar: package/package.cfg.xdc.inc
ti_syslink_ipc_rtos.tar: lib/debug/ti.syslink.ipc.rtos.ae674
ti_syslink_ipc_rtos.tar: lib/release/ti.syslink.ipc.rtos.ae674
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_syslink_ipc_rtos.tar.dep
endif
package/rel/ti_syslink_ipc_rtos/ti/syslink/ipc/rtos/package/package.rel.xml:

ti_syslink_ipc_rtos.tar: package/rel/ti_syslink_ipc_rtos.xdc.inc package/rel/ti_syslink_ipc_rtos/ti/syslink/ipc/rtos/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_syslink_ipc_rtos.xdc.inc,package/rel/ti_syslink_ipc_rtos.tar.dep)


release release,ti_syslink_ipc_rtos: all ti_syslink_ipc_rtos.tar
clean:: .clean
	-$(RM) ti_syslink_ipc_rtos.tar
	-$(RM) package/rel/ti_syslink_ipc_rtos.xdc.inc
	-$(RM) package/rel/ti_syslink_ipc_rtos.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/debug))
    $(shell $(MKDIR) lib/debug)
endif
ifeq (,$(wildcard lib/release))
    $(shell $(MKDIR) lib/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/debug))
    $(shell $(MKDIR) package/lib/lib/debug)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/package))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/..))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/..)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/../..))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/../..)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/../../cfg))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/../../cfg)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/shMem))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/shMem)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr)
endif
ifeq (,$(wildcard package/lib/lib/release))
    $(shell $(MKDIR) package/lib/lib/release)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/package))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/package)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/..))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/..)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/../..))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/../..)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/../../cfg))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/../../cfg)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/shMem))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/shMem)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/shMemMgr)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.ipc.rtos/syslinkMemMgr/tilerMemMgr)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.syslink.ipc.rtos.pjt
